=== ldibanyez/livelinkeddata/MemoryExperiments/NetworkDefs/Network.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!ELEMENT network (participant)*>
<!ATTLIST network
    type (random|erdos) #IMPLIED
    participants CDATA #IMPLIED
    edges CDATA #IMPLIED
    density CDATA #IMPLIED
    connected (True|False) #IMPLIED
>
<!ELEMENT participant (host,port,basedata,dynamic,source*)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ATTLIST participant
    id CDATA #REQUIRED>
<!ELEMENT basedata (#PCDATA)>
<!ELEMENT dynamic (insert,delete)>
<!ELEMENT insert (#PCDATA)>
<!ELEMENT delete (#PCDATA)>
<!ELEMENT source (view)*>
<!ATTLIST source
    id CDATA #REQUIRED>
<!ELEMENT view (subject,predicate,object)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT predicate (#PCDATA)>
<!ELEMENT object (#PCDATA)>

=== ldibanyez/livelinkeddata/MemoryExperiments/NetworkDefs/Ring-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE network SYSTEM 'Network.dtd'>

<network>
    <participant id="participant1">
        <host>http://localhost</host>
        <port>20501</port>
        <basedata>http://localhost/~luisdanielibanesgonzalez/datasets/MicroBase.nt</basedata>
        <dynamic>
            <insert>1.0 </insert>
            <delete>0.0</delete>
        </dynamic> 
        <source id="participant2">
            <view>
                <subject/>
                <predicate>&lt;http://dbpedia.org/ontology/deathPlace&gt;
                </predicate>
                <object/>
            </view>
            <!--
            <view>
                <subject></subject>
                <predicate>&lt;http://dbpedia.org/ontology/deathPlace&gt;
                </predicate>
                <object></object>
            </view>
            -->
        </source>
            <!--
        <source id="participant3">
            <view>
                <subject></subject>
                <predicate>&lt;http://dbpedia.org/ontology/deathPlace&gt;
                </predicate>
                <object></object>
            </view>
        </source>
            -->
    </participant>
    <participant id="participant2">
        <host>http://localhost</host>
        <port>20502</port>
        <basedata>http://localhost/~luisdanielibanesgonzalez/datasets/MicroBase.nt</basedata>
        <dynamic>
            <insert>1.0 </insert>
            <delete>0.0</delete>
        </dynamic> 
        <source id="participant3">
            <view>
                <subject/>
                <predicate>&lt;http://dbpedia.org/ontology/deathPlace&gt;
                </predicate>
                <object/>
            </view>
        </source>
    </participant>
    <participant id="participant3">
        <host>http://localhost</host>
        <port>20503</port>
        <basedata>http://localhost/~luisdanielibanesgonzalez/datasets/MicroBase.nt</basedata>
        <dynamic>
            <insert>1.0</insert>
            <delete>0.0</delete>
        </dynamic> 
        <source id="participant1">
            <view>
                <subject/>
                <predicate>&lt;http://dbpedia.org/ontology/deathPlace&gt;
                </predicate>
                <object/>
            </view>
        </source>
    </participant>
</network>
